"""empty message

Revision ID: 0f5387fbc878
Revises: 3066a23f9f5c
Create Date: 2020-10-20 20:48:29.603739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5387fbc878'
down_revision = '3066a23f9f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('g_id', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('t_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 't_id')
    op.drop_column('category', 'g_id')
    # ### end Alembic commands ###
