"""empty message

Revision ID: 236809064498
Revises: 3571ad86ee2d
Create Date: 2020-10-21 10:36:04.408942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236809064498'
down_revision = '3571ad86ee2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_number', sa.Integer(), nullable=False),
    sa.Column('factory_name', sa.String(length=64), nullable=False),
    sa.Column('factory_person', sa.String(length=64), nullable=False),
    sa.Column('factory_phone', sa.Integer(), nullable=False),
    sa.Column('factory_address', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dress_code', sa.Integer(), nullable=False),
    sa.Column('factory_number', sa.Integer(), nullable=False),
    sa.Column('pricing', sa.Integer(), nullable=False),
    sa.Column('supply_num', sa.Integer(), nullable=False),
    sa.Column('supply_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('nick_name', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('avatar_url', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('signature', sa.String(length=512), nullable=True),
    sa.Column('postal', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('nick_name')
    )
    op.create_table('pro_sup',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'supplier_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pro_sup')
    op.drop_table('user')
    op.drop_table('supply')
    op.drop_table('supplier')
    # ### end Alembic commands ###
