"""empty message

Revision ID: 2c23552cf7aa
Revises: 562fd7927400
Create Date: 2020-10-26 09:11:42.963453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c23552cf7aa'
down_revision = '562fd7927400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address_info', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_column('user', 'address_info')
    # ### end Alembic commands ###
