"""empty message

Revision ID: 3066a23f9f5c
Revises: 752eb51b1a1c
Create Date: 2020-10-20 11:33:07.998211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3066a23f9f5c'
down_revision = '752eb51b1a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_url', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'img_url')
    # ### end Alembic commands ###
