"""empty message

Revision ID: 3571ad86ee2d
Revises: d83b8115577d
Create Date: 2020-10-21 08:23:34.403550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3571ad86ee2d'
down_revision = 'd83b8115577d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('one_category_id', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('two_category_id', sa.Integer(), nullable=True))
    op.drop_column('category', 't_id')
    op.drop_column('category', 'g_id')
    op.add_column('product', sa.Column('dress_brand', sa.String(length=256), nullable=False))
    op.add_column('product', sa.Column('dress_code', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('dress_color', sa.String(length=256), nullable=False))
    op.add_column('product', sa.Column('dress_date', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('dress_img_url', sa.String(length=256), nullable=False))
    op.add_column('product', sa.Column('dress_info', sa.String(length=512), nullable=False))
    op.add_column('product', sa.Column('dress_price', sa.String(length=64), nullable=False))
    op.add_column('product', sa.Column('dress_size', sa.String(length=256), nullable=False))
    op.add_column('product', sa.Column('dress_status', sa.String(length=256), nullable=False))
    op.add_column('product', sa.Column('one_category_id', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('two_category_id', sa.Integer(), nullable=False))
    op.drop_column('product', 'title')
    op.drop_column('product', 'content')
    op.drop_column('product', 'factory_price')
    op.drop_column('product', 'img_url')
    op.drop_column('product', 'category_type')
    op.drop_column('product', 'clicks')
    op.drop_column('product', 'color')
    op.drop_column('product', 'selling_price')
    op.drop_column('product', 'size')
    op.drop_column('product', 'digest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('digest', mysql.VARCHAR(length=512), nullable=False))
    op.add_column('product', sa.Column('size', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('product', sa.Column('selling_price', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('product', sa.Column('color', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('product', sa.Column('clicks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('category_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('img_url', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('product', sa.Column('factory_price', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('product', sa.Column('content', mysql.TEXT(), nullable=False))
    op.add_column('product', sa.Column('title', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('product', 'two_category_id')
    op.drop_column('product', 'one_category_id')
    op.drop_column('product', 'dress_status')
    op.drop_column('product', 'dress_size')
    op.drop_column('product', 'dress_price')
    op.drop_column('product', 'dress_info')
    op.drop_column('product', 'dress_img_url')
    op.drop_column('product', 'dress_date')
    op.drop_column('product', 'dress_color')
    op.drop_column('product', 'dress_code')
    op.drop_column('product', 'dress_brand')
    op.add_column('category', sa.Column('g_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('category', sa.Column('t_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('category', 'two_category_id')
    op.drop_column('category', 'one_category_id')
    # ### end Alembic commands ###
