"""empty message

Revision ID: 4d9e3b174393
Revises: 2c23552cf7aa
Create Date: 2020-10-27 11:36:25.999463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9e3b174393'
down_revision = '2c23552cf7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('user_mobile', sa.String(length=11), nullable=True),
    sa.Column('user_title', sa.String(length=100), nullable=True),
    sa.Column('user_files_url', sa.String(length=100), nullable=True),
    sa.Column('user_message', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_message')
    # ### end Alembic commands ###
