"""empty message

Revision ID: 752eb51b1a1c
Revises: 
Create Date: 2020-10-20 09:52:36.886549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752eb51b1a1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grop_name', sa.String(length=64), nullable=False),
    sa.Column('type_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('color', sa.String(length=256), nullable=False),
    sa.Column('size', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('factory_price', sa.String(length=64), nullable=False),
    sa.Column('selling_price', sa.String(length=64), nullable=False),
    sa.Column('digest', sa.String(length=512), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
