"""empty message

Revision ID: 7e32bcb82ce8
Revises: e01af82a82c1
Create Date: 2020-10-29 21:31:00.623673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e32bcb82ce8'
down_revision = 'e01af82a82c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flow', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flow', type_='foreignkey')
    op.drop_column('flow', 'product_id')
    # ### end Alembic commands ###
