"""empty message

Revision ID: 893322302c4a
Revises: 8fcbbe992327
Create Date: 2020-10-29 15:14:57.269191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893322302c4a'
down_revision = '8fcbbe992327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('goods_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flow')
    # ### end Alembic commands ###
