"""empty message

Revision ID: 8fcbbe992327
Revises: b568313e959a
Create Date: 2020-10-29 09:30:59.961231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcbbe992327'
down_revision = 'b568313e959a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color', sa.Column('s', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('color', 's')
    # ### end Alembic commands ###
