"""empty message

Revision ID: b568313e959a
Revises: 05c6c66e88fc
Create Date: 2020-10-29 09:09:42.243082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b568313e959a'
down_revision = '05c6c66e88fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color', sa.Column('code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('color', 'code')
    # ### end Alembic commands ###
