"""empty message

Revision ID: cd539a9372d2
Revises: e8eaea0f6438
Create Date: 2020-10-29 16:42:47.972939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd539a9372d2'
down_revision = 'e8eaea0f6438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'dress_size')
    op.drop_column('product', 'dress_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('dress_color', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('product', sa.Column('dress_size', mysql.VARCHAR(length=256), nullable=False))
    # ### end Alembic commands ###
