"""empty message

Revision ID: d83b8115577d
Revises: 0f5387fbc878
Create Date: 2020-10-20 21:15:44.257569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83b8115577d'
down_revision = '0f5387fbc878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'category_type')
    # ### end Alembic commands ###
