"""empty message

Revision ID: e01af82a82c1
Revises: cd539a9372d2
Create Date: 2020-10-29 20:02:30.593628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01af82a82c1'
down_revision = 'cd539a9372d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('prices', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow', 'prices')
    # ### end Alembic commands ###
