"""empty message

Revision ID: e8eaea0f6438
Revises: 893322302c4a
Create Date: 2020-10-29 15:43:52.731110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8eaea0f6438'
down_revision = '893322302c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('color', sa.String(length=11), nullable=True))
    op.add_column('flow', sa.Column('size', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow', 'size')
    op.drop_column('flow', 'color')
    # ### end Alembic commands ###
