"""empty message

Revision ID: ead40b231730
Revises: 4d9e3b174393
Create Date: 2020-10-28 08:24:41.941004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ead40b231730'
down_revision = '4d9e3b174393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_message', sa.Column('user_grade', sa.Integer(), nullable=True))
    op.drop_column('user_message', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_message', sa.Column('user_id', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('user_message', 'user_grade')
    # ### end Alembic commands ###
