"""empty message

Revision ID: ec978e6b2438
Revises: b41a8ccc6a4c
Create Date: 2020-10-22 23:23:49.947608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec978e6b2438'
down_revision = 'b41a8ccc6a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('mobile', table_name='user')
    op.drop_index('name', table_name='user')
    op.drop_index('nick_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('nick_name', 'user', ['nick_name'], unique=True)
    op.create_index('name', 'user', ['name'], unique=True)
    op.create_index('mobile', 'user', ['mobile'], unique=True)
    # ### end Alembic commands ###
